### ISSUE TITLE
npm install node-sass@4.1.1 fails for node < 7.6

### ISSUE THREAD

**Issue by itsashis4u** [hueniverse/sntp#23]
Info: 
```
{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
```

Installing `node-sass@4.1.1` tries to build `node-sass` and runs into the following error:

```
> node-sass@4.1.1 install node_modules/node-sass
> node scripts/install.js

node_modules/sntp/lib/index.js:19
exports.time = async function (options = {}) {
                     ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/hawk/lib/index.js:5:16)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.1.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Rakk4403** [comment]
Same as me

**Comment by warrenseymour** [comment]
Looks like this is being caused by an upstream consumer - see https://github.com/request/request/issues/2891

**Comment by hueniverse** [comment]
Not my problem.
